<?php
/**
 * @file
 * Defines an example shipping method for testing and development.
 */
module_load_include('inc', 'commerce_acs', 'include/commerce_acs_wsdl');
/**
 * Implements hook_menu().
 */

function commerce_acs_menu() {
  $items = array();
  $items['admin/commerce/config/shipping/methods/acs/edit'] = array(
    'title' => 'Edit',
    'description' => 'Configure the ACS shipping method.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array(
      'commerce_acs_settings_form'
    ) ,
    'access arguments' => array(
      'administer shipping'
    ) ,
    'file' => 'include/commerce_acs.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_INLINE,
    'weight' => 0,
  );
  return $items;
}
/**
 * Implements hook_commerce_shipping_method_info().
 */

function commerce_acs_commerce_shipping_method_info() {
  $shipping_methods = array();
  $shipping_methods['acs'] = array(
    'title' => t('ACS Method') ,
    'description' => t('Defines ACS rate.') ,
  );
  return $shipping_methods;
}
/**
 * Implements hook_commerce_shipping_service_info().
 */

function commerce_acs_commerce_shipping_service_info() {
  $shipping_services = array();
  $shipping_services['acs'] = array(
    'title' => t('ACS shipping service') ,
    'description' => t('ACS Shipping service.') ,
    'display_title' => t('Shipping') ,
    'shipping_method' => 'acs',
    'price_component' => 'shipping',
    'callbacks' => array(
      'rate' => 'commerce_acs_rate',
      'details_form' => 'commerce_acs_details_form',
      'details_form_validate' => 'commerce_acs_details_form_validate',
      'details_form_submit' => 'commerce_acs_details_form_submit',
    ) ,
  );
  return $shipping_services;
}
/**
 * Shipping service callback: returns a base price array for a shipping service
 * calculated for the given order.
 */

function commerce_acs_rate($shipping_service, $order) {
  $order_wrapper = entity_metadata_wrapper('commerce_order', $order);
  $settings = variable_get('acs_settings');
  $credentials = variable_get('acs_credentials');
  $data = commerce_acs_physical_data($settings, $order);
  $shipping = $order_wrapper->commerce_customer_shipping->commerce_customer_address->value();
  $validate = commerce_acs_wsdl_address_validation($credentials, $shipping);
  
  if ($validate) {
    $data['to'] = $validate;
    (int)$data['xrewsh'] = 2;
    $data['asf_poso'] = '';
    $data['zone'] = '';
    $data['date_par'] = '';
    $data['products'] = '';
    $price = commerce_acs_wsdl_price_by_volume($credentials, $data);
    dpm($price);
    return array(
      'amount' => $price * 100,
      'currency_code' => $order_wrapper->commerce_order_total->currency_code->value() ,
      'data' => array() ,
    );
  }
  else {
    return array(
      'amount' => 0,
      'currency_code' => $order_wrapper->commerce_order_total->currency_code->value() ,
      'data' => array() ,
    );
  }
}
/**
 * Shipping service callback: returns the example shipping service details form.
 */

function commerce_acs_details_form($pane_form, &$pane_values, $checkout_pane, $order, $shipping_service) {
  $form = array();
  $pane_values['service_details']+= array(
    'name' => '',
    'express' => '',
  );
  $form['express'] = array(
    '#type' => 'checkbox',
    '#title' => t('Express delivery') ,
    '#description' => t('Express delivery is really fast and you need to pay extra for this service.') ,
    '#default_value' => $pane_values['service_details']['express'],
    '#ajax' => array(
      'callback' => 'commerce_shipping_recalculate_services_refresh',
      'wrapper' => 'commerce-shipping-service-ajax-wrapper',
    ) ,
  );
  return $form;
}
/**
 * Shipping service callback: validates the example shipping service details.
 */

function commerce_acs_details_form_validate($details_form, $details_values, $shipping_service, $order, $form_parents) {
  /*
  if (strlen($details_values['name']) < 2) {
    form_set_error(implode('][', array_merge($form_parents, array(
      'name'
    ))) , t('You must enter a name two or more characters long.'));
    // Even though the form error is enough to stop the submission of the form,
    // it's not enough to stop it from a Commerce standpoint because of the
    // combined validation / submission going on per-pane in the checkout form.
    return FALSE;
  }   */
}
/**
 * Shipping service callback: increases the shipping line item's unit price if
 * express delivery was selected.
 */

function commerce_acs_details_form_submit($details_form, $details_values, $line_item) {
  
  if ($details_values['express']) {
    $line_item_wrapper = entity_metadata_wrapper('commerce_line_item', $line_item);
    // Build a price array for the express delivery fee.
    $express_price = array(
      'amount' => 1500,
      'currency_code' => $line_item_wrapper->commerce_unit_price->currency_code->value() ,
      'data' => array() ,
    );
    // Add the express upcharge to the line item unit price.
    $line_item_wrapper->commerce_unit_price->amount = $line_item_wrapper->commerce_unit_price->amount->value() + 1500;
    // Add the express delivery fee component to the unit price.
    $line_item_wrapper->commerce_unit_price->data = commerce_price_component_add($line_item_wrapper->commerce_unit_price->value() , 'example_shipping_service_express', $express_price, TRUE, FALSE);
  }
}
/**
 * Implements hook_commerce_price_component_type_info().
 */

function commerce_acs_commerce_price_component_type_info() {
  return array(
    'example_shipping_service_express' => array(
      'title' => t('Express delivery') ,
      'weight' => 20,
    ) ,
    'acs_cod_fee' => array(
      'title' => t('Cash on delivery Acs') ,
      'weight' => 20,
    ) ,
  );
}
function commerce_acs_default_rules_configuration() {
  $items = array();
  $val = 2000;
  $name = t('ACS Cash on Delivery');
  $items['rules_commerce_acs_cod']= entity_import('rules_config','{ "rules_commerce_acs_cod" : {
    "LABEL" : "Commerce ACS COD",
    "PLUGIN" : "reaction rule",
    "OWNER" : "rules",
    "REQUIRES" : [
      "commerce_payment",
      "commerce_shipping",
      "commerce_acs",
      "commerce_line_item"
    ],
    "ON" : { "commerce_shipping_calculate_rate" : [] },
    "IF" : [
      { "commerce_payment_selected_payment_method" : {
          "commerce_order" : [ "commerce-line-item:order" ],
          "method_id" : "commerce_cod"
        }
      },
      { "commerce_shipping_compare_shipping_service" : { "commerce_order" : [ "commerce-line-item:order" ], "service" : "acs" } }
    ],
    "DO" : [
      { "commerce_acs_rules_action_calculate_cod_price" : {
          "USING" : { "order" : [ "commerce-line-item:order" ] },
          "PROVIDE" : { "cod_price" : { "cod_price" : "COD price" } }
        }
      },
      { "commerce_line_item_unit_price_add" : {
          "commerce_line_item" : [ "commerce_line_item" ],
          "amount" : [ "cod-price" ],
          "component_name" : "acs_cod_fee",
          "round_mode" : "0"
        }
      }
    ]
  }
}');
  return $items;
}
 
/**
 * Implement hook_rules_action_info().
 */
function commerce_acs_rules_action_info() {
  return array(
    'commerce_acs_rules_action_calculate_cod_price' => array(
      'label' => t('Calculate ACS COD price'),
      'group' => t('Custom'),
      'parameter' => array(
        'order' => array(
          'type' => 'commerce_order',
          'label' => t('Order ID'),
          'description' => t('Enter the order ID.'),
        ),
      ),
      'provides' => array(
        'cod_price' => array(
          'type' => 'decimal',
          'label' => t('COD price'),
        ),
      ),
    ),
  
  );
}
 
 
// This callback creates the hashed string by using the parameters provided through rules' UI
function commerce_acs_rules_action_calculate_cod_price($order) {

 $order_wrapper = entity_metadata_wrapper('commerce_order', $order);
 $shipping = $order_wrapper->commerce_customer_shipping->commerce_customer_address->value();
 $settings = variable_get('acs_settings');
 $credentials = variable_get('acs_credentials');
 $data = commerce_acs_physical_data($settings, $order);
  $validate = commerce_acs_wsdl_address_validation($credentials, $shipping);
  if ($validate) {
    $data['to'] = $validate;
    (int)$data['xrewsh'] = 2;
    $data['asf_poso'] = '';
    $data['zone'] = '';
    $data['date_par'] = '';
    $data['products'] = 'ΑΝ';
    $ammountDet = commerce_acs_wsdl_price_by_volume($credentials,$data, true);
    $ammountDet_ar = explode('|', $ammountDet);
    $price = $ammountDet_ar[1]*100;
  }

  return array(
    'cod_price' => (float) $price,
  );
}
function commerce_acs_form_alter(&$form, &$form_state, $form_id) {
    dpm($form_id);
  switch ($form_id) {
    case 'commerce_checkout_form_shipping':
      drupal_add_js(drupal_get_path('module', 'commerce_acs').'/recalculate.js');
    break;
}

}
