<?php
/**
 * @file commerce_acs_address_validation.module
 * Demonstrates the addition of a new pane to the checkout system.
 */
/**
 * Implements info_page() function.
 */

function commerce_acs_address_validation_info_page() {
  return array(
    '#markup' => t('Provides a pane for ACS Courier address validation.') ,
  );
}
/**
 * Implements hook_commerce_checkout_pane_info().
 */

function commerce_acs_address_validation_commerce_checkout_pane_info() {
  $panes['commerce_acs_address_validation'] = array(
    'title' => t('Checkout Pane ACS validation') ,
    'base' => 'commerce_acs_address_validation_pane',
    // The checkout page where this should be displayed by default.
    'page' => 'checkout',
    'weight' => - 5,
  );
  return $panes;
}

function commerce_acs_address_validation_pane_checkout_form($form, &$form_state, $checkout_pane, $order) {
  drupal_add_js(drupal_get_path('module', 'commerce_acs_address_validation') . '/fill_address.js');
  drupal_add_css(drupal_get_path('module', 'commerce_acs_address_validation') . '/fill_address.css');
  $pane_form['validate'] = array(
    '#type' => 'button',
    '#value' => t('Validate Shipping Address') ,
    '#weight' => - 1,
    '#ajax' => array(
      'callback' => 'ajax_wsdl_validate_callback',
      'wrapper' => 'acs-validate-address-info',
    ) ,
  );
  $pane_form['adress_validate_info'] = array(
    '#type' => 'markup',
    '#prefix' => '<div id="acs-validate-address-info">',
    '#suffix' => '</div>',
    '#markup' => '',
  );
  return $pane_form;
}

function ajax_wsdl_validate_callback($form, &$form_state) {
  module_load_include('inc', 'commerce_acs', 'includes/commerce_acs.api');
  $response = commerce_acs_address_suggestions($form_state['values']['customer_profile_shipping']['commerce_customer_address'][LANGUAGE_NONE][0]);
  $table = commerce_acs_address_suggestions_table($response);
  $form['buttons']['adress_validate_info'] = array(
    '#type' => 'markup',
    '#prefix' => '<div id="acs-validate-address-info">',
    '#suffix' => '</div',
    '#markup' => drupal_render($table) ,
  );
  return $form['buttons']['adress_validate_info'];
}
